"""add predict loop config table

Revision ID: 1b5715fb9232
Revises: c1a4e8f7b2d9
Create Date: 2026-07-21 16:03:54.578263
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '1b5715fb9232'
down_revision = 'c1a4e8f7b2d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict_loop_config',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_seconds', sa.Integer(), nullable=False),
    sa.Column('rotation_hours', sa.Float(), nullable=False),
    sa.Column('rotation_anchor', sa.DateTime(), nullable=False),
    sa.Column('headlines_per_source', sa.Integer(), nullable=False),
    sa.Column('near_dup_window_hours', sa.Float(), nullable=False),
    sa.Column('near_dup_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict_loop_config')
    # ### end Alembic commands ###
