"""add hypothesis, hypothesis_belief, anticipatory_loop_config tables

Revision ID: 44e2f028ba06
Revises: e75c8c2b0b69
Create Date: 2026-07-22 15:09:23.037911
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '44e2f028ba06'
down_revision = 'e75c8c2b0b69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anticipatory_loop_config',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_seconds', sa.Integer(), nullable=False),
    sa.Column('min_gap_threshold', sa.Float(), nullable=False),
    sa.Column('max_open_hypotheses', sa.Integer(), nullable=False),
    sa.Column('discovery_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypothesis',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # Created as plain VARCHAR here, then ALTERed to the existing
    # 'predictiondirection' enum type via raw SQL below -- NOT
    # sa.Enum(..., create_type=False) inline. That flag turned out not to
    # reliably suppress SQLAlchemy's CREATE TYPE emission for a Postgres
    # ENUM referenced by name from a fresh sa.Enum() instance inside
    # op.create_table (confirmed against real production Postgres:
    # DuplicateObject: type "predictiondirection" already exists, even
    # with create_type=False set) -- 'predictiondirection' already exists,
    # created by 26dca4757036_add_prediction_table's Prediction.direction
    # column. Raw ALTER COLUMN TYPE sidesteps the DDL compiler's
    # visit_enum path entirely. SQLite has no native enum type so this
    # only ever bites in production Postgres, not the local/test suite.
    sa.Column('direction_if_yes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='hypothesisstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_outcome', sa.Boolean(), nullable=True),
    sa.Column('position_side', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traded_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traded_quantity', sa.Float(), nullable=True),
    sa.Column('exit_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE hypothesis ALTER COLUMN direction_if_yes TYPE predictiondirection "
            "USING direction_if_yes::predictiondirection"
        )
    op.create_index(op.f('ix_hypothesis_market_id'), 'hypothesis', ['market_id'], unique=True)
    op.create_index(op.f('ix_hypothesis_status'), 'hypothesis', ['status'], unique=False)
    op.create_index(op.f('ix_hypothesis_symbol'), 'hypothesis', ['symbol'], unique=False)
    op.create_index(op.f('ix_hypothesis_traded_order_id'), 'hypothesis', ['traded_order_id'], unique=False)
    op.create_table('hypothesis_belief',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hypothesis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('p_model', sa.Float(), nullable=False),
    sa.Column('p_market', sa.Float(), nullable=False),
    sa.Column('gap', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('OPENED', 'ADDED', 'TRIMMED', 'EXITED', 'HELD', 'NO_GAP', name='hypothesisaction'), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_belief_created_at'), 'hypothesis_belief', ['created_at'], unique=False)
    op.create_index(op.f('ix_hypothesis_belief_hypothesis_id'), 'hypothesis_belief', ['hypothesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_belief_hypothesis_id'), table_name='hypothesis_belief')
    op.drop_index(op.f('ix_hypothesis_belief_created_at'), table_name='hypothesis_belief')
    op.drop_table('hypothesis_belief')
    op.drop_index(op.f('ix_hypothesis_traded_order_id'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_symbol'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_status'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_market_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_table('anticipatory_loop_config')
    # ### end Alembic commands ###
