"""initial journal tables

Revision ID: 60993312d4d0
Revises: 
Create Date: 2026-07-20 03:16:41.965636
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '60993312d4d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_snapshot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('universe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bar_start', sa.DateTime(), nullable=True),
    sa.Column('bar_end', sa.DateTime(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.Column('bar_row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER_LIVE', name='runmode'), nullable=False),
    sa.Column('strategy_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('git_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('is_validation_run', sa.Boolean(), nullable=False),
    sa.Column('validation_access_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('avg_holding_hours', sa.Float(), nullable=True),
    sa.Column('exposure_pct', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_run_created_at'), 'experiment_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiment_run_data_snapshot_id'), 'experiment_run', ['data_snapshot_id'], unique=False)
    op.create_index(op.f('ix_experiment_run_is_validation_run'), 'experiment_run', ['is_validation_run'], unique=False)
    op.create_index(op.f('ix_experiment_run_mode'), 'experiment_run', ['mode'], unique=False)
    op.create_index(op.f('ix_experiment_run_strategy_name'), 'experiment_run', ['strategy_name'], unique=False)
    op.create_table('news_item_record',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('routed_symbols', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_item_record_ingested_at'), 'news_item_record', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_news_item_record_published_at'), 'news_item_record', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_item_record_source'), 'news_item_record', ['source'], unique=False)
    op.create_table('reconciliation_report',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('backtest_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backtest_expected_return_pct', sa.Float(), nullable=False),
    sa.Column('realized_return_pct', sa.Float(), nullable=False),
    sa.Column('divergence_pct', sa.Float(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=False),
    sa.Column('within_tolerance', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['experiment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_halt_event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_equity', sa.Float(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_halt_event_run_id'), 'risk_halt_event', ['run_id'], unique=False)
    op.create_index(op.f('ix_risk_halt_event_timestamp'), 'risk_halt_event', ['timestamp'], unique=False)
    op.create_table('trade_record',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='tradeside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('exit_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_record_broker_order_id'), 'trade_record', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_trade_record_run_id'), 'trade_record', ['run_id'], unique=False)
    op.create_index(op.f('ix_trade_record_symbol'), 'trade_record', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_record_timestamp'), 'trade_record', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_record_timestamp'), table_name='trade_record')
    op.drop_index(op.f('ix_trade_record_symbol'), table_name='trade_record')
    op.drop_index(op.f('ix_trade_record_run_id'), table_name='trade_record')
    op.drop_index(op.f('ix_trade_record_broker_order_id'), table_name='trade_record')
    op.drop_table('trade_record')
    op.drop_index(op.f('ix_risk_halt_event_timestamp'), table_name='risk_halt_event')
    op.drop_index(op.f('ix_risk_halt_event_run_id'), table_name='risk_halt_event')
    op.drop_table('risk_halt_event')
    op.drop_table('reconciliation_report')
    op.drop_index(op.f('ix_news_item_record_source'), table_name='news_item_record')
    op.drop_index(op.f('ix_news_item_record_published_at'), table_name='news_item_record')
    op.drop_index(op.f('ix_news_item_record_ingested_at'), table_name='news_item_record')
    op.drop_table('news_item_record')
    op.drop_index(op.f('ix_experiment_run_strategy_name'), table_name='experiment_run')
    op.drop_index(op.f('ix_experiment_run_mode'), table_name='experiment_run')
    op.drop_index(op.f('ix_experiment_run_is_validation_run'), table_name='experiment_run')
    op.drop_index(op.f('ix_experiment_run_data_snapshot_id'), table_name='experiment_run')
    op.drop_index(op.f('ix_experiment_run_created_at'), table_name='experiment_run')
    op.drop_table('experiment_run')
    op.drop_table('data_snapshot')
    # ### end Alembic commands ###
