"""add last_cycle_at heartbeat to predict_loop_config and anticipatory_loop_config

Revision ID: a722f3ec8a05
Revises: 44e2f028ba06
Create Date: 2026-07-22 17:57:05.471581
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a722f3ec8a05'
down_revision = '44e2f028ba06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anticipatory_loop_config', sa.Column('last_cycle_at', sa.DateTime(), nullable=True))
    op.add_column('predict_loop_config', sa.Column('last_cycle_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict_loop_config', 'last_cycle_at')
    op.drop_column('anticipatory_loop_config', 'last_cycle_at')
    # ### end Alembic commands ###
