"""add enabled_sources to predict_loop_config

Revision ID: b4e1c7a92f0d
Revises: d3f8c1a9b7e2
Create Date: 2026-07-24 09:00:00.000000
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b4e1c7a92f0d'
down_revision = 'd3f8c1a9b7e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predict_loop_config', sa.Column('enabled_sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predict_loop_config', 'enabled_sources')
    # ### end Alembic commands ###
